namespace SymmetricalEncryptionDemo
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.ComboBox_AlgorithmList = new System.Windows.Forms.ComboBox();
            this.Button_GenerateProperites = new System.Windows.Forms.Button();
            this.AutoGeneratedPropertiesTitleLabel = new System.Windows.Forms.Label();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.KeyLabel = new System.Windows.Forms.Label();
            this.KeyTextBox = new System.Windows.Forms.TextBox();
            this.IVLabel = new System.Windows.Forms.Label();
            this.IVTextBox = new System.Windows.Forms.TextBox();
            this.Button_EncryptMessage = new System.Windows.Forms.Button();
            this.EncryptionPropertiesTitleLabel = new System.Windows.Forms.Label();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.MessageLabel = new System.Windows.Forms.Label();
            this.MessageTextBox = new System.Windows.Forms.TextBox();
            this.EncryptedLabel = new System.Windows.Forms.Label();
            this.EncryptedMessageTextBox = new System.Windows.Forms.TextBox();
            this.Button_DecryptMessage = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.label3 = new System.Windows.Forms.Label();
            this.DisplayEncryptedMessageTextBox = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.DecryptedMessageTextBox = new System.Windows.Forms.TextBox();
            this.Button_GetBenchmarkTimes = new System.Windows.Forms.Button();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.DecryptionTimeLabel = new System.Windows.Forms.Label();
            this.EncryptionTimeLabel = new System.Windows.Forms.Label();
            this.EncryptionTimeBenchmark = new System.Windows.Forms.Label();
            this.DecryptionTimeBenchmark = new System.Windows.Forms.Label();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(12, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(207, 25);
            this.label1.TabIndex = 0;
            this.label1.Text = "Pick Algorithm Method";
            // 
            // ComboBox_AlgorithmList
            // 
            this.ComboBox_AlgorithmList.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ComboBox_AlgorithmList.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ComboBox_AlgorithmList.FormattingEnabled = true;
            this.ComboBox_AlgorithmList.Location = new System.Drawing.Point(12, 37);
            this.ComboBox_AlgorithmList.Name = "ComboBox_AlgorithmList";
            this.ComboBox_AlgorithmList.Size = new System.Drawing.Size(207, 26);
            this.ComboBox_AlgorithmList.TabIndex = 1;
            // 
            // Button_GenerateProperites
            // 
            this.Button_GenerateProperites.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Button_GenerateProperites.Location = new System.Drawing.Point(12, 90);
            this.Button_GenerateProperites.Name = "Button_GenerateProperites";
            this.Button_GenerateProperites.Size = new System.Drawing.Size(207, 41);
            this.Button_GenerateProperites.TabIndex = 2;
            this.Button_GenerateProperites.Text = "Generate Key and IV";
            this.Button_GenerateProperites.UseVisualStyleBackColor = true;
            this.Button_GenerateProperites.Click += new System.EventHandler(this.Button_GenerateProperites_Click);
            // 
            // AutoGeneratedPropertiesTitleLabel
            // 
            this.AutoGeneratedPropertiesTitleLabel.AutoSize = true;
            this.AutoGeneratedPropertiesTitleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AutoGeneratedPropertiesTitleLabel.Location = new System.Drawing.Point(600, 9);
            this.AutoGeneratedPropertiesTitleLabel.Name = "AutoGeneratedPropertiesTitleLabel";
            this.AutoGeneratedPropertiesTitleLabel.Size = new System.Drawing.Size(245, 25);
            this.AutoGeneratedPropertiesTitleLabel.TabIndex = 4;
            this.AutoGeneratedPropertiesTitleLabel.Text = "Auto-Generated Properties";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tableLayoutPanel1.Controls.Add(this.KeyLabel, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.KeyTextBox, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.IVLabel, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.IVTextBox, 1, 1);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(605, 37);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(382, 94);
            this.tableLayoutPanel1.TabIndex = 5;
            // 
            // KeyLabel
            // 
            this.KeyLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.KeyLabel.AutoSize = true;
            this.KeyLabel.Location = new System.Drawing.Point(3, 15);
            this.KeyLabel.Name = "KeyLabel";
            this.KeyLabel.Size = new System.Drawing.Size(108, 17);
            this.KeyLabel.TabIndex = 0;
            this.KeyLabel.Text = "Key:";
            // 
            // KeyTextBox
            // 
            this.KeyTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.KeyTextBox.Location = new System.Drawing.Point(117, 12);
            this.KeyTextBox.Name = "KeyTextBox";
            this.KeyTextBox.ReadOnly = true;
            this.KeyTextBox.Size = new System.Drawing.Size(262, 22);
            this.KeyTextBox.TabIndex = 1;
            // 
            // IVLabel
            // 
            this.IVLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.IVLabel.AutoSize = true;
            this.IVLabel.Location = new System.Drawing.Point(3, 62);
            this.IVLabel.Name = "IVLabel";
            this.IVLabel.Size = new System.Drawing.Size(108, 17);
            this.IVLabel.TabIndex = 2;
            this.IVLabel.Text = "IV:";
            // 
            // IVTextBox
            // 
            this.IVTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.IVTextBox.Location = new System.Drawing.Point(117, 59);
            this.IVTextBox.Name = "IVTextBox";
            this.IVTextBox.ReadOnly = true;
            this.IVTextBox.Size = new System.Drawing.Size(262, 22);
            this.IVTextBox.TabIndex = 3;
            // 
            // Button_EncryptMessage
            // 
            this.Button_EncryptMessage.Location = new System.Drawing.Point(12, 192);
            this.Button_EncryptMessage.Name = "Button_EncryptMessage";
            this.Button_EncryptMessage.Size = new System.Drawing.Size(207, 41);
            this.Button_EncryptMessage.TabIndex = 6;
            this.Button_EncryptMessage.Text = "Encrypt Message";
            this.Button_EncryptMessage.UseVisualStyleBackColor = true;
            this.Button_EncryptMessage.Click += new System.EventHandler(this.Button_EncryptMessage_Click);
            // 
            // EncryptionPropertiesTitleLabel
            // 
            this.EncryptionPropertiesTitleLabel.AutoSize = true;
            this.EncryptionPropertiesTitleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.EncryptionPropertiesTitleLabel.Location = new System.Drawing.Point(600, 164);
            this.EncryptionPropertiesTitleLabel.Name = "EncryptionPropertiesTitleLabel";
            this.EncryptionPropertiesTitleLabel.Size = new System.Drawing.Size(197, 25);
            this.EncryptionPropertiesTitleLabel.TabIndex = 7;
            this.EncryptionPropertiesTitleLabel.Text = "Encryption Properties";
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tableLayoutPanel2.Controls.Add(this.MessageLabel, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.MessageTextBox, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.EncryptedLabel, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.EncryptedMessageTextBox, 1, 1);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(605, 192);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 2;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(382, 94);
            this.tableLayoutPanel2.TabIndex = 8;
            // 
            // MessageLabel
            // 
            this.MessageLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.MessageLabel.AutoSize = true;
            this.MessageLabel.Location = new System.Drawing.Point(3, 15);
            this.MessageLabel.Name = "MessageLabel";
            this.MessageLabel.Size = new System.Drawing.Size(108, 17);
            this.MessageLabel.TabIndex = 0;
            this.MessageLabel.Text = "Message:";
            // 
            // MessageTextBox
            // 
            this.MessageTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.MessageTextBox.Location = new System.Drawing.Point(117, 12);
            this.MessageTextBox.Name = "MessageTextBox";
            this.MessageTextBox.Size = new System.Drawing.Size(262, 22);
            this.MessageTextBox.TabIndex = 1;
            // 
            // EncryptedLabel
            // 
            this.EncryptedLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.EncryptedLabel.AutoSize = true;
            this.EncryptedLabel.Location = new System.Drawing.Point(3, 62);
            this.EncryptedLabel.Name = "EncryptedLabel";
            this.EncryptedLabel.Size = new System.Drawing.Size(108, 17);
            this.EncryptedLabel.TabIndex = 2;
            this.EncryptedLabel.Text = "Encrypted:";
            // 
            // EncryptedMessageTextBox
            // 
            this.EncryptedMessageTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.EncryptedMessageTextBox.Location = new System.Drawing.Point(117, 59);
            this.EncryptedMessageTextBox.Name = "EncryptedMessageTextBox";
            this.EncryptedMessageTextBox.ReadOnly = true;
            this.EncryptedMessageTextBox.Size = new System.Drawing.Size(262, 22);
            this.EncryptedMessageTextBox.TabIndex = 3;
            // 
            // Button_DecryptMessage
            // 
            this.Button_DecryptMessage.Location = new System.Drawing.Point(12, 353);
            this.Button_DecryptMessage.Name = "Button_DecryptMessage";
            this.Button_DecryptMessage.Size = new System.Drawing.Size(207, 41);
            this.Button_DecryptMessage.TabIndex = 9;
            this.Button_DecryptMessage.Text = "Decrypt Message";
            this.Button_DecryptMessage.UseVisualStyleBackColor = true;
            this.Button_DecryptMessage.Click += new System.EventHandler(this.Button_DecryptMessage_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(600, 325);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(198, 25);
            this.label2.TabIndex = 10;
            this.label2.Text = "Decryption Properties";
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 2;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tableLayoutPanel3.Controls.Add(this.label3, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.DisplayEncryptedMessageTextBox, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.label4, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.DecryptedMessageTextBox, 1, 1);
            this.tableLayoutPanel3.Location = new System.Drawing.Point(605, 353);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 2;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(382, 94);
            this.tableLayoutPanel3.TabIndex = 11;
            // 
            // label3
            // 
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 15);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(108, 17);
            this.label3.TabIndex = 0;
            this.label3.Text = "Encrypted:";
            // 
            // DisplayEncryptedMessageTextBox
            // 
            this.DisplayEncryptedMessageTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.DisplayEncryptedMessageTextBox.Location = new System.Drawing.Point(117, 12);
            this.DisplayEncryptedMessageTextBox.Name = "DisplayEncryptedMessageTextBox";
            this.DisplayEncryptedMessageTextBox.ReadOnly = true;
            this.DisplayEncryptedMessageTextBox.Size = new System.Drawing.Size(262, 22);
            this.DisplayEncryptedMessageTextBox.TabIndex = 1;
            // 
            // label4
            // 
            this.label4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(3, 62);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(108, 17);
            this.label4.TabIndex = 2;
            this.label4.Text = "Derypted:";
            // 
            // DecryptedMessageTextBox
            // 
            this.DecryptedMessageTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.DecryptedMessageTextBox.Location = new System.Drawing.Point(117, 59);
            this.DecryptedMessageTextBox.Name = "DecryptedMessageTextBox";
            this.DecryptedMessageTextBox.ReadOnly = true;
            this.DecryptedMessageTextBox.Size = new System.Drawing.Size(262, 22);
            this.DecryptedMessageTextBox.TabIndex = 3;
            // 
            // Button_GetBenchmarkTimes
            // 
            this.Button_GetBenchmarkTimes.Location = new System.Drawing.Point(12, 575);
            this.Button_GetBenchmarkTimes.Name = "Button_GetBenchmarkTimes";
            this.Button_GetBenchmarkTimes.Size = new System.Drawing.Size(207, 41);
            this.Button_GetBenchmarkTimes.TabIndex = 12;
            this.Button_GetBenchmarkTimes.Text = "Get Encrypt / Decrypt Times";
            this.Button_GetBenchmarkTimes.UseVisualStyleBackColor = true;
            this.Button_GetBenchmarkTimes.Click += new System.EventHandler(this.Button_GetBenchmarkTimes_Click);
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 2;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.Controls.Add(this.DecryptionTimeBenchmark, 1, 1);
            this.tableLayoutPanel4.Controls.Add(this.DecryptionTimeLabel, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.EncryptionTimeLabel, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.EncryptionTimeBenchmark, 0, 1);
            this.tableLayoutPanel4.Location = new System.Drawing.Point(324, 575);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 2;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 32.11009F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 67.88991F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(663, 109);
            this.tableLayoutPanel4.TabIndex = 13;
            // 
            // DecryptionTimeLabel
            // 
            this.DecryptionTimeLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.DecryptionTimeLabel.AutoSize = true;
            this.DecryptionTimeLabel.Location = new System.Drawing.Point(334, 8);
            this.DecryptionTimeLabel.Name = "DecryptionTimeLabel";
            this.DecryptionTimeLabel.Size = new System.Drawing.Size(326, 17);
            this.DecryptionTimeLabel.TabIndex = 1;
            this.DecryptionTimeLabel.Text = "Decryption Time:";
            this.DecryptionTimeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // EncryptionTimeLabel
            // 
            this.EncryptionTimeLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.EncryptionTimeLabel.AutoSize = true;
            this.EncryptionTimeLabel.Location = new System.Drawing.Point(3, 8);
            this.EncryptionTimeLabel.Name = "EncryptionTimeLabel";
            this.EncryptionTimeLabel.Size = new System.Drawing.Size(325, 17);
            this.EncryptionTimeLabel.TabIndex = 0;
            this.EncryptionTimeLabel.Text = "Encryption Time:";
            this.EncryptionTimeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // EncryptionTimeBenchmark
            // 
            this.EncryptionTimeBenchmark.AutoSize = true;
            this.EncryptionTimeBenchmark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.EncryptionTimeBenchmark.Location = new System.Drawing.Point(3, 34);
            this.EncryptionTimeBenchmark.Name = "EncryptionTimeBenchmark";
            this.EncryptionTimeBenchmark.Size = new System.Drawing.Size(325, 75);
            this.EncryptionTimeBenchmark.TabIndex = 2;
            this.EncryptionTimeBenchmark.Text = "No Benchmark Made";
            this.EncryptionTimeBenchmark.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // DecryptionTimeBenchmark
            // 
            this.DecryptionTimeBenchmark.AutoSize = true;
            this.DecryptionTimeBenchmark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DecryptionTimeBenchmark.Location = new System.Drawing.Point(334, 34);
            this.DecryptionTimeBenchmark.Name = "DecryptionTimeBenchmark";
            this.DecryptionTimeBenchmark.Size = new System.Drawing.Size(326, 75);
            this.DecryptionTimeBenchmark.TabIndex = 3;
            this.DecryptionTimeBenchmark.Text = "No Benchmark Made";
            this.DecryptionTimeBenchmark.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(999, 696);
            this.Controls.Add(this.tableLayoutPanel4);
            this.Controls.Add(this.Button_GetBenchmarkTimes);
            this.Controls.Add(this.tableLayoutPanel3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.Button_DecryptMessage);
            this.Controls.Add(this.tableLayoutPanel2);
            this.Controls.Add(this.EncryptionPropertiesTitleLabel);
            this.Controls.Add(this.Button_EncryptMessage);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.AutoGeneratedPropertiesTitleLabel);
            this.Controls.Add(this.Button_GenerateProperites);
            this.Controls.Add(this.ComboBox_AlgorithmList);
            this.Controls.Add(this.label1);
            this.Name = "MainForm";
            this.Text = "Symmetrical Encryption Demo";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox ComboBox_AlgorithmList;
        private System.Windows.Forms.Button Button_GenerateProperites;
        private System.Windows.Forms.Label AutoGeneratedPropertiesTitleLabel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label KeyLabel;
        private System.Windows.Forms.TextBox KeyTextBox;
        private System.Windows.Forms.Label IVLabel;
        private System.Windows.Forms.TextBox IVTextBox;
        private System.Windows.Forms.Button Button_EncryptMessage;
        private System.Windows.Forms.Label EncryptionPropertiesTitleLabel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.Label MessageLabel;
        private System.Windows.Forms.TextBox MessageTextBox;
        private System.Windows.Forms.Label EncryptedLabel;
        private System.Windows.Forms.TextBox EncryptedMessageTextBox;
        private System.Windows.Forms.Button Button_DecryptMessage;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox DisplayEncryptedMessageTextBox;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox DecryptedMessageTextBox;
        private System.Windows.Forms.Button Button_GetBenchmarkTimes;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.Label DecryptionTimeLabel;
        private System.Windows.Forms.Label EncryptionTimeLabel;
        private System.Windows.Forms.Label DecryptionTimeBenchmark;
        private System.Windows.Forms.Label EncryptionTimeBenchmark;
    }
}

